#!/bin/bash

# Text pipe filter to only keep lines ending in any of the chosen chars given as input parameter

if [ -p /dev/stdin ]; then  # don't hang if input is empty

	#check_input
	if [ $# -lt 1 ]; then
			echo "Input parameters expected. Specify ending characters of the lines to return."
			echo "./(command) (string with wanted ending chars)"
			exit
	fi

	CHARSTOEND=$1

	while IFS= read line; do
		match="false"
		lastCharInPipe=${line: -1}
		for (( i=0; i<${#CHARSTOEND}; i++ )); do
			if [ "${CHARSTOEND:$i:1}" == "$lastCharInPipe" ]; then
				match="true"
				break
			fi
		done
		if [ $match == "true" ]; then  # print line if there has been no matching char 
			echo "$line"
		fi
	done
fi 
